export const CELL_CLICK = 'CELL_CLICK';
export const END_TURN = 'END_TURN';
export const UNIT_PURCHASE = 'UNIT_PURCHASE';

export const CELL_SELECTED = 'CELL_SELECTED';
export const CELL_UNSELECTED = 'CELL_UNSELECTED';
export const MOVEMENT_INITIATED = 'MOVEMENT_INITIATED';
